name: Reusable - Delete all repositories in ACR (Azure CLI)

on:
  workflow_dispatch:
    inputs:
      acr-name:
        description: Name of the Azure Container Registry (sin .azurecr.io)
        required: true
        type: string
      dry-run:
        description: If true, do not delete, only print actions
        required: false
        default: false
        type: boolean


jobs:
  delete-repos:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Login to Azure (Service Principal)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.SERVICE_PRINCIPAL }}

      # 🔑 Login al data-plane del ACR (evita "authentication required")
      - name: Login to ACR (data-plane)
        env:
          ACR_NAME: ${{ inputs.acr-name }}
        shell: bash
        run: |
          set -euo pipefail
          # --expose-token evita depender de docker; silencioso para logs
          az acr login -n "${ACR_NAME}" --expose-token --only-show-errors 1>/dev/null

      - name: Delete repositories in ACR
        env:
          ACR_NAME: ${{ inputs.acr-name }}
          DRY_RUN: ${{ inputs['dry-run'] }}
        shell: bash
        run: |
          set -euo pipefail

          # Retry ligero por propagación de permisos
          for i in {1..5}; do
            if repos=$(az acr repository list -n "${ACR_NAME}" -o tsv 2>/dev/null); then
              break
            fi
            echo "ACR not ready yet, retrying in 5s ($i/5)..."
            sleep 5
          done

          if [[ -z "${repos:-}" ]]; then
            echo "No repositories found. Nothing to delete."
            exit 0
          fi

          echo "Found repositories:" && echo "${repos}" | sed 's/^/ - /'

          if [[ "${DRY_RUN}" == "true" ]]; then
            echo "DRY RUN enabled. Skipping deletions."
            exit 0
          fi

          while IFS= read -r repo; do
            [[ -z "${repo}" ]] && continue
            echo "Deleting repository: ${repo}"
            az acr repository delete -n "${ACR_NAME}" --repository "${repo}" --yes --only-show-errors 1>/dev/null
          done <<< "${repos}"

          echo "Done deleting repositories in ${ACR_NAME}."
