name: Scheduled - Delete ACR repos

on:
  schedule:
    - cron: '0 1 * * *'   # 01:00 UTC diario
  workflow_dispatch: {}

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-acr-delete-repos.yml
    with:
      # Si es manual, toma el input; si es schedule, será false por defecto
      dry-run: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.dry-run == 'true' }}
    secrets:
      SERVICE_PRINCIPAL: ${{ secrets.SERVICE_PRINCIPAL }}
      ACR_NAME: ${{ secrets.ACR_NAME }}